{% set name = "types-psycopg2" %}
{% set version = "2.9.21.20260408" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: bb65cd12f53b6633077fd782607a33065e1f3bf585219c9f786b61ad2b72211c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}

test:
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for psycopg2
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdsmith
