{% set name = "types-psycopg2" %}
{% set version = "2.9.21.20240417" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-psycopg2-{{ version }}.tar.gz
  sha256: 05db256f4a459fb21a426b8e7fca0656c3539105ff0208eaf6bdaf406a387087

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for psycopg2
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - tdsmith
